feat: Make the contract support any ERC-20 token
dewdrop-labs/transverse-contracts pull request #13
Opened 2024-12-18 16:22 UTC by 1nonlypiece

closes #10

2024-12-18 16:30 UTC, 1nonlypiece commented
@Dprof-in-tech

2024-12-18 17:03 UTC, Dprof-in-tech commented
> @Dprof-in-tech 

I would review it in a bit ser. Thank you

2024-12-19 16:26 UTC, Dprof-in-tech requested changes
Did something totally different.

What you are meant to do was to make the Wallet contract to accept ERC20 tokens, but you wrote a totally different contract. Which isn’t what is needed.

So you should study the Wallet contracts and modify the functions that uses usdt to accept any erc20 token, then you should add new tests and modify existing tests to capture your changes.

2024-12-22 03:16 UTC, 1nonlypiece commented
@Dprof-in-tech okay, give me some time to study wallet contracts & do code changes.

2025-01-23 07:09 UTC, closed without merging